spring:
  datasource:
    url: jdbc:postgresql://${PGSQL_SERVICE_HOST}:${PGSQL_SERVICE_PORT}/job_fusion_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:migration
    baseline-version: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 86400000

open:
  api:
    serverUrl: ${SERVER_URL}

app:
  admin:
    email: ${ADMIN_PLATFORM_USERNAME}
    password: ${ADMIN_PLATFORM_PASSWORD}
  otp:
    expire-minutes: 5
  loginUrl: https://fe-project-2ljo.vercel.app/
